name: 'Enforce Conventional Commits'
#
on:
  pull_request:
    branches: [ '*' ]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Check Commit Style
      uses: amannn/action-semantic-pull-request@v4
      with:
        types: |
          feat
          fix
          chore
          docs
          refactor
          test
          build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

